extern void draw_image(unsigned char *data);
extern void set_bkg_tiles(unsigned char x, unsigned char y, unsigned char w, unsigned char h, unsigned char *tiles);
extern void set_bkg_data(unsigned char first_tile, unsigned char nb_tiles, unsigned char *data);
extern void delay(unsigned int d);
extern void loadMap(unsigned char bank, unsigned char address[], unsigned char width, unsigned char height);
extern void loadEncounter(char* memory, unsigned char bank);
extern void set_sprite_prop(unsigned char nb, unsigned char prop);
extern void chooseWeaponBanked(unsigned char characterID);
extern void choosePotionBanked(unsigned char characterID);
extern void disable_interrupts();
extern void OAM_START_TRANSFER();
extern unsigned char eqStatistic(unsigned char id, unsigned char statistic);
extern unsigned char armorValue(unsigned char value);
extern unsigned char selectedItem[];
extern unsigned char characterStateMemory[];
extern void showBufferedMessage();
extern unsigned char waitpad(unsigned char mask);
extern unsigned char joypad();
extern char rand();
extern unsigned int randw();
extern void initrand (unsigned int seed);
extern unsigned char logoData[];
extern char map[];
extern unsigned char message[];
extern void checkEvents(unsigned int eventPointer, unsigned char bank);
extern void showMessage(unsigned char bank, unsigned char flag, const char* memoryLocation);
extern unsigned char overworldPosX, overworldPosY;
extern void renderMessageOnWindow(unsigned char flag, const char* memoryLocation);
extern void renderBufferedMessage();
extern char woodenFight[];
extern unsigned char showOptions(unsigned char bank, unsigned char flag, const char* title, const char* first, const char* second, const char* third, const char* fourth);
extern char* enemyList;
extern char* charactersList;
extern void loadBankedTileset(unsigned char bank, unsigned char first_tile, unsigned char nb_tiles, unsigned char * data);
extern unsigned char runFunction(char* target, char* skill);
extern char messageBuffer[64];
extern void replaceInBuffer(unsigned char bank, char* value);
extern void replaceInBufferInt(int value);
extern void copyToBuffer(unsigned char bank, char* value);
extern char mainCharacterMemory[];
extern char enemyMemory[];
extern char mainCharacterSkillMemory[];
extern char enemySkillMemory[];
extern char testFight[];
extern char encounterHeader;
extern void add_TIM(void(*int_handler)(void));
extern void interruptIdle();
extern void enable_interrupts();
extern void deleteItem(unsigned char characterID, unsigned char ID, unsigned char am);
extern unsigned char hasItem(unsigned char ID, unsigned char am);
extern void rollWindowIn(unsigned char target);
extern void rollWindowBack(unsigned char target);
extern void set_win_tiles(unsigned char x, unsigned char y, unsigned char w, unsigned char h, unsigned char *tiles);
extern void rollWindowOut();
extern void copyToBuffer(unsigned char bank, char value[]);
extern void copyMemory(char* source, char* destination, unsigned char length, unsigned char bank);
typedef void BankedFunction(unsigned char);
extern void runAdditionalBankedFunction(BankedFunction function, unsigned char id);
extern unsigned char bitflag[];
